### ISSUE TITLE
Sometimes screen gets stuck on loading animation.

### ISSUE THREAD

**Issue by jalaj-k** [jalaj-k/todox#14]
**Describe the bug**
The window gets stuck on the loading animation in the todos pages. the animations continue forever.

**Expected behavior**
It should show the list of todos

**Screenshots**

**Devices**
All

**Possible Reason**
Console logs show that it is possibly because the `database.get` function is being called before the class is instantiated.

**Comment by tsturtz** [comment]
Hi! I'm checking this one out 😄
