### ISSUE TITLE
Multiline description shown in single line in todo-item

### ISSUE THREAD

**Issue by jalaj-k** [jalaj-k/todox#8]
**Describe the bug**
When a  multiline description is added to a todo, then it is shown in single line, which can be irritating.

**To Reproduce**
1. Create a new todo.
2. Give it a multi-line description.
3. View it in its respective list
4. Expand it.

**Comment by stefanuslim** [comment]
Can i work on this?

**Comment by jalaj-k** [comment]
@stefanuslim Sure.
